### PR TITLE
feat: add an option to run `make` in release-mod

### PR DESCRIPTION
**Pull request by JonathanDUFOUR**
We are now able to build the project in release-mod using `make all RELEASE=<whatever_while_not_empty>`

### CODE REVIEW

**Review by alisterd51 — CHANGES_REQUESTED** [review]
if I do `make RELEASE=debug` (it compiles) then `make RELEASE=release` (nothing)
Is there a solution to correct this problem without having to delete files?

**Comment by alisterd51** [comment]
also, this is not the right type of commit,
This does not add a feature to our code base (gratOS) but just changes the build method.
it is therefore a `build` type commit

https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

**Comment by JonathanDUFOUR** [comment]
> if I do `make RELEASE=debug` (it compiles) then `make RELEASE=release` (nothing) Is there a solution to correct this problem without having to delete files?

This is expected. I implemented it as a flag instead of an option, following the same behavior as `cargo`. That means that running `make <rule>` will run it in dev/debug mode while running `make <rule> RELEASE=<whatever_while_non_empty>` will run it in release mode. Typically, you may run `make re RELEASE=1`.

**Comment by alisterd51** [comment]
> > if I do `make RELEASE=debug` (it compiles) then `make RELEASE=release` (nothing) Is there a solution to correct this problem without having to delete files?
> 
> This is expected. I implemented it as a flag instead of an option, following the same behavior as `cargo`. That means that running `make <rule>` will run it in dev/debug mode while running `make <rule> RELEASE=<whatever_while_non_empty>` will run it in release mode. Typically, you may run `make re RELEASE=1`.

no, if I do `cargo build` then `cargo build --release` then `cargo build` the latter will not need to recompile unnecessarily.

**Comment by alisterd51** [comment]
an elegant solution would perhaps be to place the desired files in folders such as `build/release/` and `build/debug/`

**Comment by alisterd51** [comment]
it would be more relevant to have folders like `build/debug/` and `build/release/` so that we can test the 2 ISOs without needing a recompilation of all the sources (sometimes very long)

**Comment by JonathanDUFOUR** [comment]
I disagree because we will do the tests only in debug/dev mode and thus we will compile only in this mode until the project is considered as ready to be released. And then we will be forced to recompile every source in release mode. So the current build flag is largely enough to do that.

**Comment by JonathanDUFOUR** [comment]
The branch has been renamed, so I'll make another merge request for it. Therefore, I close this one.

**Pull request closed without merging**
